name: DotaMine
version: 0.5
author: rfsantos1996
main: com.jabyftw.dotamine.DotaMine
description: Dota on Minecraft
softdepend: [Vault,ControllableMobsAPI]
commands:
   dota:
     description: Main command
     usage: Use /dota (forcestart/ranking/tp/spectate/join [ranged/meele/leave])
permissions:
   dotamine.play:
     description: Gives access to join the game
     default: true
   dotamine.spectate:
     description: Gives access to spectate the game
     default: true
   dotamine.ranking:
     description: Gives access to ranking command
     default: true
   dotamine.forcestart:
     description: Allows you force start the game
     default: op