name: DotaMine
version: 0.4
author: rfsantos1996
main: com.jabyftw.dotamine.DotaMine
description: Dota on Minecraft
softdepend: [Vault,ControllableMobsAPI]
commands:
   dota:
     description: Main command
     usage: Use /dota (forcestart/ranking/tp)
   join:
     description: Join command
     permission: dotamine.play
     usage: Use /join (meele/ranged/leave)
   spectate:
     description: Spectate command
     permission: dotamine.spectate
     usage: Use /spectate [leave]
permissions:
   dotamine.play:
     description: Gives access to join command
     default: true
   dotamine.spectate:
     description: Gives access to spectate the game on join
     default: true
   dotamine.ranking:
     description: Gives access to /dota ranking command
     default: true
   dotamine.forcestart:
     description: Allows you force start the game
     default: op